version: '3.9'

services:
  web:
    build: .
    command: >
      sh -c "python /code/manage.py migrate && 
             python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - USE_DOCKER=1
      - SECRET_KEY=my_super_secret_key
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=djangox
      - DB_USER=djangox
      - DB_PASS=djangox
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=djangox
      - POSTGRES_USER=djangox
      - POSTGRES_PASSWORD=djangox
    ports:
      - 5432:5432

volumes:
  postgres_data:
